name: ClauseBot API - CI/CD Pipeline
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

# Global default permissions - read-only by default
permissions:
  contents: read
  pull-requests: read
  actions: read

env:
  PYTHON_VERSION: '3.11'

jobs:
  test:
    name: Test & Lint
    runs-on: ubuntu-latest
    
    # Job-level permissions - read-only for test job
    permissions:
      contents: read
      pull-requests: read
    
    steps:
    - name: Checkout code
      # Pinned to v4.2.2 commit SHA for security
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
      
    - name: Set up Python
      # Pinned to v5.3.0 commit SHA
      uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b  # v5.3.0
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        
    - name: Cache pip dependencies
      # Pinned to v4.2.0 commit SHA
      uses: actions/cache@6849a6489940f00c2f30c0fb92c6274307ccb58a  # v4.2.0
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[dev]
    
    - name: Run tests with pytest
      run: |
        pytest --cov=app --cov-report=term-missing --cov-report=xml
    
    - name: Run linting
      run: |
        ruff check .
        black --check .

  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    
    # Build job gets limited write access for packages
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
      
    - name: Set up Docker Buildx
      # Pinned to v3.10.0 commit SHA
      uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349  # v3.10.0
      
    - name: Log in to GitHub Container Registry
      # Pinned to v3.3.0 commit SHA
      uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567  # v3.3.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Extract metadata
      id: meta
      # Pinned to v5.6.1 commit SHA
      uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81  # v5.6.1
      with:
        images: ghcr.io/${{ github.repository }}
        tags: |
          type=ref,event=branch
          type=semver,pattern={{version}}
          type=sha
          
    - name: Build and push Docker image
      # Pinned to v6.10.0 commit SHA
      uses: docker/build-push-action@4f58ea79222b3b9dc2c8bbdd6debcef730109a75  # v6.10.0
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
