# Gulp workflow for asset processing, linting, and minification
name: Gulp Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  gulp:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871  # v4.2.1
      
    - name: Setup Node.js
      uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6  # v4.0.4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: package-lock.json
        
    - name: Install dependencies with locked versions
      run: npm ci
      
    - name: Install Gulp CLI globally
      run: npm install -g gulp-cli
      
    - name: Run Gulp lint
      run: gulp lint
      continue-on-error: false
      
    - name: Run Gulp asset processing
      run: gulp assets
      
    - name: Run Gulp minification
      run: gulp minify
      
    - name: Run Gulp build (all tasks)
      run: gulp build
      
    - name: Upload processed assets
      uses: actions/upload-artifact@604373164c44f8a2e2d17db62b90aee2f0c18fb8  # v4.4.3
      with:
        name: gulp-assets
        path: |
          dist/
          build/
          assets/
        retention-days: 30
        
    - name: Notify on failure
      if: failure()
      uses: dawidd6/action-send-mail@6063705cefe50cb915fc53bb06d4049cae2953b2  # v3.12.0
      with:
        server_address: ${{ secrets.MAIL_SERVER }}
        server_port: ${{ secrets.MAIL_PORT }}
        username: ${{ secrets.MAIL_USERNAME }}
        password: ${{ secrets.MAIL_PASSWORD }}
        subject: 'Gulp Build Failed: ${{ github.workflow }} - ${{ github.repository }}'
        body: |
          Gulp build workflow failed!
          Repository: ${{ github.repository }}
          Branch: ${{ github.ref }}
          Commit: ${{ github.sha }}
          Author: ${{ github.actor }}
          
          Check details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        to: ${{ secrets.NOTIFICATION_EMAIL }}
        from: GitHub Actions
