# SLSA v3 generator workflow for signed artifact provenance
name: SLSA Provenance

on:
  release:
    types: [created]
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      hashes: ${{ steps.hash.outputs.hashes }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871  # v4.2.1
      
    - name: Setup Node.js
      uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6  # v4.0.4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: package-lock.json
        
    - name: Install dependencies with locked versions
      run: npm ci
      
    - name: Build project
      run: npm run build
      
    - name: Create release artifact
      run: |
        mkdir -p release-artifacts
        tar -czf release-artifacts/clausebotai-${{ github.ref_name }}.tar.gz dist/
        
    - name: Generate artifact hashes
      shell: bash
      id: hash
      run: |
        cd release-artifacts
        echo "hashes=$(sha256sum * | base64 -w0)" >> "$GITHUB_OUTPUT"
        
    - name: Upload release artifacts
      uses: actions/upload-artifact@604373164c44f8a2e2d17db62b90aee2f0c18fb8  # v4.4.3
      with:
        name: release-artifacts
        path: release-artifacts/
        retention-days: 90
        
    - name: Notify on failure
      if: failure()
      uses: dawidd6/action-send-mail@6063705cefe50cb915fc53bb06d4049cae2953b2  # v3.12.0
      with:
        server_address: ${{ secrets.MAIL_SERVER }}
        server_port: ${{ secrets.MAIL_PORT }}
        username: ${{ secrets.MAIL_USERNAME }}
        password: ${{ secrets.MAIL_PASSWORD }}
        subject: 'SLSA Build Failed: ${{ github.workflow }} - ${{ github.repository }}'
        body: |
          SLSA provenance workflow build failed!
          Repository: ${{ github.repository }}
          Release: ${{ github.ref_name }}
          Commit: ${{ github.sha }}
          
          Check details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        to: ${{ secrets.NOTIFICATION_EMAIL }}
        from: GitHub Actions

  provenance:
    needs: [build]
    permissions:
      actions: read
      id-token: write
      contents: write
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@5a775b367a56d5bd118a224a811bba288150a563  # v2.0.0
    with:
      base64-subjects: ${{ needs.build.outputs.hashes }}
      upload-assets: true
      provenance-name: clausebotai-provenance.intoto.jsonl
      
  sbom:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Checkout code
      uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871  # v4.2.1
      
    - name: Setup Node.js
      uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6  # v4.0.4
      with:
        node-version: '20.x'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Generate SBOM
      run: npx @cyclonedx/cyclonedx-npm --output-file sbom.json
      
    - name: Install cosign
      uses: sigstore/cosign-installer@dc72c7d5c4d10cd6bcb8cf6e3fd625a9e5e537da  # v3.7.0
      
    - name: Sign SBOM with cosign
      run: |
        cosign sign-blob --yes sbom.json --output-signature sbom.json.sig
        
    - name: Upload SBOM
      uses: actions/upload-artifact@604373164c44f8a2e2d17db62b90aee2f0c18fb8  # v4.4.3
      with:
        name: sbom-signed
        path: |
          sbom.json
          sbom.json.sig
        retention-days: 90
        
    - name: Notify on failure
      if: failure()
      uses: dawidd6/action-send-mail@6063705cefe50cb915fc53bb06d4049cae2953b2  # v3.12.0
      with:
        server_address: ${{ secrets.MAIL_SERVER }}
        server_port: ${{ secrets.MAIL_PORT }}
        username: ${{ secrets.MAIL_USERNAME }}
        password: ${{ secrets.MAIL_PASSWORD }}
        subject: 'SLSA SBOM Generation Failed: ${{ github.workflow }} - ${{ github.repository }}'
        body: |
          SLSA SBOM generation failed!
          Repository: ${{ github.repository }}
          Release: ${{ github.ref_name }}
          
          Check details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        to: ${{ secrets.NOTIFICATION_EMAIL }}
        from: GitHub Actions
