services:
  - type: web
    name: clausebot-api-ts
    env: node
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: API_KEYS
        sync: false  # Set in Render dashboard
      - key: ALLOWED_ORIGINS
        sync: false  # Set in Render dashboard
