name: Smoke Tests

on:
  push:
    branches: [main]
    paths:
      - 'frontend/**'
  pull_request:
    branches: [main]
    paths:
      - 'frontend/**'

jobs:
  smoke-test:
    name: Smoke Test - Verify App Mounts
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      
      - name: Install dependencies
        working-directory: frontend
        run: npm ci
      
      - name: Install Playwright browsers
        working-directory: frontend
        run: npx playwright install --with-deps chromium
      
      - name: Build production bundle
        working-directory: frontend
        run: npm run build
      
      - name: Start preview server
        working-directory: frontend
        run: |
          npm run preview &
          echo $! > preview.pid
          # Wait for server to start
          npx wait-on http://localhost:4173 --timeout 30000
      
      - name: Run smoke tests
        working-directory: frontend
        env:
          E2E_BASE_URL: http://localhost:4173
        run: npx playwright test tests/e2e/smoke.spec.ts
      
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: frontend/playwright-report/
          retention-days: 7
      
      - name: Stop preview server
        if: always()
        working-directory: frontend
        run: |
          if [ -f preview.pid ]; then
            kill $(cat preview.pid) || true
          fi
      
      - name: Comment PR with results
        if: github.event_name == 'pull_request' && always()
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const status = '${{ job.status }}';
            const body = status === 'success' 
              ? '✅ Smoke tests passed - app mounts and renders correctly'
              : '❌ Smoke tests failed - check logs for details';
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });

